# Generated by Django 4.2.1 on 2023-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_description', models.TextField()),
                ('payment_method_name', models.CharField(max_length=255)),
            ],
        ),
    ]
