# Generated by Django 3.2.12 on 2023-07-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refunds',
            options={'verbose_name_plural': 'Refunds'},
        ),
    ]
