# Generated by Django 4.2.1 on 2023-06-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='order_history',
            new_name='orderhistory',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
