# Generated by Django 4.2.1 on 2023-06-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_first_name_person_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='orderhistory',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=55),
        ),
    ]
