# Generated by Django 3.2.12 on 2023-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('product', models.ManyToManyField(to='inventory.Product')),
            ],
        ),
    ]
